version: "3.8"

networks:
  corp:
    driver: bridge

services:
  electricity-tariffs-api:
    container_name: electricity-tariffs-api
    build:
      context: ./
      cache_from:
        - electricity-tariffs-base-img:nx-dev
      dockerfile: ./apps/back/Dockerfile
      args:
        NODE_ENV: "development"
    image: electricity-tariffs-api:nx-dev
    ports:
      - 4939
    environment:
      NODE_ENV: "development"
      ELECTRICITY_TARIFFS_API: "http://host.docker.internal:3400/electricity-tariffs"
      PORT: 4939
    networks:
      - corp
    restart: on-failure

  electricity-tariffs-front:
    container_name: electricity-tariffs-front
    build:
      context: ./
      cache_from:
        - nginx:1.23.4
      dockerfile: ./apps/front/Dockerfile
      args:
        NODE_ENV: "development"
    image: electricity-tariffs-front:nx-dev
    ports:
      - 4900:80
    environment:
      NODE_ENV: "development"
      PORT: 4900
    networks:
      - corp
    restart: on-failure
